const std = @import("std");

/// Comptime case-insensitive perfect hash map for O(1) language code lookups.
const CiStringMap = std.StaticStringMapWithEql([]const u8, std.ascii.eqlIgnoreCase);

const lang_map = CiStringMap.initComptime(.{
    .{ "eng", "English" },
    .{ "en", "English" },
    .{ "heb", "Hebrew" },
    .{ "he", "Hebrew" },
    .{ "iw", "Hebrew" },
    .{ "spa", "Spanish" },
    .{ "es", "Spanish" },
    .{ "fra", "French" },
    .{ "fre", "French" },
    .{ "fr", "French" },
    .{ "deu", "German" },
    .{ "ger", "German" },
    .{ "de", "German" },
    .{ "ita", "Italian" },
    .{ "it", "Italian" },
    .{ "rus", "Russian" },
    .{ "ru", "Russian" },
    .{ "por", "Portuguese" },
    .{ "pt", "Portuguese" },
    .{ "ara", "Arabic" },
    .{ "ar", "Arabic" },
    .{ "zho", "Chinese" },
    .{ "chi", "Chinese" },
    .{ "zh", "Chinese" },
    .{ "jpn", "Japanese" },
    .{ "ja", "Japanese" },
    .{ "kor", "Korean" },
    .{ "ko", "Korean" },
    .{ "hin", "Hindi" },
    .{ "hi", "Hindi" },
    .{ "tur", "Turkish" },
    .{ "tr", "Turkish" },
    .{ "pol", "Polish" },
    .{ "pl", "Polish" },
    .{ "ukr", "Ukrainian" },
    .{ "uk", "Ukrainian" },
    .{ "nld", "Dutch" },
    .{ "dut", "Dutch" },
    .{ "nl", "Dutch" },
    .{ "swe", "Swedish" },
    .{ "sv", "Swedish" },
    .{ "nor", "Norwegian" },
    .{ "nob", "Norwegian" },
    .{ "nno", "Norwegian" },
    .{ "no", "Norwegian" },
    .{ "dan", "Danish" },
    .{ "da", "Danish" },
    .{ "fin", "Finnish" },
    .{ "fi", "Finnish" },
    .{ "ell", "Greek" },
    .{ "gre", "Greek" },
    .{ "el", "Greek" },
    .{ "ces", "Czech" },
    .{ "cze", "Czech" },
    .{ "cs", "Czech" },
    .{ "hun", "Hungarian" },
    .{ "hu", "Hungarian" },
    .{ "ron", "Romanian" },
    .{ "rum", "Romanian" },
    .{ "ro", "Romanian" },
    .{ "bul", "Bulgarian" },
    .{ "bg", "Bulgarian" },
    .{ "hrv", "Croatian" },
    .{ "hr", "Croatian" },
    .{ "srp", "Serbian" },
    .{ "sr", "Serbian" },
    .{ "slv", "Slovenian" },
    .{ "sl", "Slovenian" },
    .{ "slk", "Slovak" },
    .{ "slo", "Slovak" },
    .{ "sk", "Slovak" },
    .{ "lit", "Lithuanian" },
    .{ "lt", "Lithuanian" },
    .{ "lav", "Latvian" },
    .{ "lv", "Latvian" },
    .{ "est", "Estonian" },
    .{ "et", "Estonian" },
    .{ "cat", "Catalan" },
    .{ "ca", "Catalan" },
    .{ "vie", "Vietnamese" },
    .{ "vi", "Vietnamese" },
    .{ "tha", "Thai" },
    .{ "th", "Thai" },
    .{ "ind", "Indonesian" },
    .{ "id", "Indonesian" },
    .{ "msa", "Malay" },
    .{ "may", "Malay" },
    .{ "ms", "Malay" },
    .{ "fil", "Tagalog" },
    .{ "tgl", "Tagalog" },
    .{ "tl", "Tagalog" },
    .{ "fas", "Persian" },
    .{ "per", "Persian" },
    .{ "fa", "Persian" },
    .{ "urd", "Urdu" },
    .{ "ur", "Urdu" },
    .{ "ben", "Bengali" },
    .{ "bn", "Bengali" },
    .{ "tam", "Tamil" },
    .{ "ta", "Tamil" },
    .{ "tel", "Telugu" },
    .{ "te", "Telugu" },
    .{ "kan", "Kannada" },
    .{ "kn", "Kannada" },
    .{ "mal", "Malayalam" },
    .{ "ml", "Malayalam" },
    .{ "mar", "Marathi" },
    .{ "mr", "Marathi" },
    .{ "pan", "Punjabi" },
    .{ "pa", "Punjabi" },
    .{ "guj", "Gujarati" },
    .{ "gu", "Gujarati" },
    .{ "kat", "Georgian" },
    .{ "geo", "Georgian" },
    .{ "ka", "Georgian" },
    .{ "hye", "Armenian" },
    .{ "arm", "Armenian" },
    .{ "hy", "Armenian" },
    .{ "aze", "Azerbaijani" },
    .{ "az", "Azerbaijani" },
    .{ "kaz", "Kazakh" },
    .{ "kk", "Kazakh" },
    .{ "uzb", "Uzbek" },
    .{ "uz", "Uzbek" },
    .{ "mon", "Mongolian" },
    .{ "mn", "Mongolian" },
    .{ "lat", "Latin" },
    .{ "la", "Latin" },
    .{ "isl", "Icelandic" },
    .{ "ice", "Icelandic" },
    .{ "is", "Icelandic" },
    .{ "gle", "Irish" },
    .{ "ga", "Irish" },
    .{ "cym", "Welsh" },
    .{ "wel", "Welsh" },
    .{ "cy", "Welsh" },
    .{ "eus", "Basque" },
    .{ "baq", "Basque" },
    .{ "eu", "Basque" },
    .{ "alb", "Albanian" },
    .{ "sqi", "Albanian" },
    .{ "sq", "Albanian" },
    .{ "mkd", "Macedonian" },
    .{ "mac", "Macedonian" },
    .{ "mk", "Macedonian" },
    .{ "bos", "Bosnian" },
    .{ "bs", "Bosnian" },
    .{ "bel", "Belarusian" },
    .{ "be", "Belarusian" },
    .{ "yid", "Yiddish" },
    .{ "yi", "Yiddish" },
    .{ "epo", "Esperanto" },
    .{ "eo", "Esperanto" },
});

/// Comptime case-insensitive map for regional BCP 47 codes with subtags.
const regional_map = CiStringMap.initComptime(.{
    .{ "zh-hans", "Chinese (Simplified)" },
    .{ "zh-cn", "Chinese (Simplified)" },
    .{ "zh-hant", "Chinese (Traditional)" },
    .{ "zh-tw", "Chinese (Traditional)" },
    .{ "zh-hk", "Chinese (Traditional)" },
    .{ "pt-br", "Portuguese (Brazil)" },
    .{ "es-419", "Spanish (Latin America)" },
});

/// Maps ISO 639-1, ISO 639-2 (B/T), and regional BCP 47 language codes to human-readable English names.
pub fn getLanguageName(code: []const u8) ?[]const u8 {
    // Check regional codes first (includes subtags)
    if (regional_map.get(code)) |name| return name;

    // Strip subtags like "-US", "_US", "-GB", etc. for base lookup
    const clean_code = if (std.mem.indexOfAny(u8, code, "-_")) |dash_idx|
        code[0..dash_idx]
    else
        code;

    return lang_map.get(clean_code);
}

test "getLanguageName mapping" {
    try std.testing.expectEqualStrings("English", getLanguageName("eng").?);
    try std.testing.expectEqualStrings("English", getLanguageName("en").?);
    try std.testing.expectEqualStrings("English", getLanguageName("en-US").?);
    try std.testing.expectEqualStrings("Hebrew", getLanguageName("heb").?);
    try std.testing.expectEqualStrings("Hebrew", getLanguageName("he").?);
    try std.testing.expectEqualStrings("Spanish", getLanguageName("spa").?);
    try std.testing.expectEqualStrings("Russian", getLanguageName("rus").?);
    try std.testing.expectEqualStrings("Chinese (Simplified)", getLanguageName("zh-CN").?);
    try std.testing.expect(getLanguageName("und") == null);
}
