name: Deploy to Production

on:
  workflow_run:
    workflows: ["Build & Semantic Release Arch Binary"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to padre.rus9n.com
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment:
      name: production
      url: https://padre.rus9n.com
    
    steps:
      - name: Trigger Remote Installation
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          # This script handles downloading the latest release, securely stopping the daemon, and restarting it!
          script: |
            curl -sL https://raw.githubusercontent.com/borisgk/sratim/main/scripts/install.sh | sudo bash
